slug: network-delay-time
patterns:
- Depth-First Search
- Breadth-First Search
- Graph Theory
- Heap (Priority Queue)
- Shortest Path
description_rst: "You are given a network of ``n`` nodes, labeled from ``1`` to ``n``. You\nare also given ``times``, a list of travel times as directed edges\n``times[i] = (u``\\ :sub:```i```\\ ``, v``\\ :sub:```i```\\ ``, w``\\ :sub:```i```\\ ``)``,\nwhere ``u``\\ :sub:```i``` is the source node, ``v``\\ :sub:```i``` is the\ntarget node, and ``w``\\ :sub:```i``` is the time it takes for a signal\nto travel from source to target.\n\nWe will send a signal from a given node ``k``. Return *the* **minimum**\n*time it takes for all the* ``n`` *nodes to receive the signal*. If it\nis impossible for all the ``n`` nodes to receive the signal, return\n``-1``.\n\n \n\n**Example 1:**\n\n|image1|\n\n::\n\n\n   Input: times = [[2,1,1],[2,3,1],[3,4,1]], n = 4, k = 2\n   Output: 2\n\n**Example 2:**\n\n::\n\n\n   Input: times = [[1,2,1]], n = 2, k = 1\n   Output: 1\n\n**Example 3:**\n\n::\n\n\n   Input: times = [[1,2,1]], n = 2, k = 2\n   Output: -1\n\n \n\n**Constraints:**\n\n- ``1 <= k <= n <= 100``\n\
  - ``1 <= times.length <= 6000``\n- ``times[i].length == 3``\n- ``1 <= u``\\ :sub:```i```\\ ``, v``\\ :sub:```i```\\ ``<= n``\n- ``u``\\ :sub:```i```\\ ``!= v``\\ :sub:```i```\n- ``0 <= w``\\ :sub:```i```\\ ``<= 100``\n- All the pairs ``(u``\\ :sub:```i```\\ ``, v``\\ :sub:```i```\\ ``)`` are\n  **unique**. (i.e., no multiple edges.)\n\n.. |image1| image:: https://assets.leetcode.com/uploads/2019/05/23/931_example_1.png\n"
solutions:
- name: Dijkstra
  explanation: ''
  complexity: ''
