slug: generate-parentheses
patterns:
- String
- Dynamic Programming
- Backtracking
description_rst: |
  Given ``n`` pairs of parentheses, write a function to *generate all
  combinations of well-formed parentheses*.

   

  **Example 1:**

  ::

     Input: n = 3
     Output: ["((()))","(()())","(())()","()(())","()()()"]

  **Example 2:**

  ::

     Input: n = 1
     Output: ["()"]

   

  **Constraints:**

  - ``1 <= n <= 8``
solutions:
- name: Backtracking
  explanation: |
    Let's construct a well-formed parentheses string of size 3 from left to right. ::

        (, (), ()(, ()((, ()((), ()(())

    Observe that

    1. we can only add ')' when the number of '(' is :math:`>` to the number of ')'
    2. we can keep adding '(' until we run out.

    We can recursively add parenthesis according to these 2 rules until we exhaust
    the limit of left and right parentheses.
  complexity: |
    | Time: :math:`O(4^n / \sqrt{n})` — Catalan number of combinations
    | Auxiliary Space: :math:`O(n)` — recursive call stack and string storage
