slug: unique-paths
patterns:
- Math
- Dynamic Programming
- Combinatorics
description_rst: "There is a robot on an ``m x n`` grid. The robot is initially located at\nthe **top-left corner** (i.e., ``grid[0][0]``). The robot tries to move\nto the **bottom-right corner** (i.e., ``grid[m - 1][n - 1]``). The robot\ncan only move either down or right at any point in time.\n\nGiven the two integers ``m`` and ``n``, return *the number of possible\nunique paths that the robot can take to reach the bottom-right corner*.\n\nThe test cases are generated so that the answer will be less than or\nequal to ``2 * 10``\\ :sup:```9```.\n\n \n\n**Example 1:**\n\n|image1|\n\n::\n\n\n   Input: m = 3, n = 7\n   Output: 28\n\n**Example 2:**\n\n::\n\n\n   Input: m = 3, n = 2\n   Output: 3\n   Explanation: From the top-left corner, there are a total of 3 ways to reach the bottom-right corner:\n   1. Right -> Down -> Down\n   2. Down -> Down -> Right\n   3. Down -> Right -> Down\n\n \n\n**Constraints:**\n\n- ``1 <= m, n <= 100``\n\n.. |image1| image:: https://assets.leetcode.com/uploads/2018/10/22/robot_maze.png\n"
solutions:
- name: Dynamic Programming
  explanation: ''
  complexity: ''
