slug: same-tree
patterns:
- Tree
- Depth-First Search
- Breadth-First Search
- Binary Tree
description_rst: |
  Given the roots of two binary trees ``p`` and ``q``, write a function to
  check if they are the same or not.

  Two binary trees are considered the same if they are structurally
  identical, and the nodes have the same value.

   

  **Example 1:**

  |image1|

  ::


     Input: p = [1,2,3], q = [1,2,3]
     Output: true

  **Example 2:**

  |image2|

  ::


     Input: p = [1,2], q = [1,null,2]
     Output: false

  **Example 3:**

  |image3|

  ::


     Input: p = [1,2,1], q = [1,1,2]
     Output: false

   

  **Constraints:**

  - The number of nodes in both trees is in the range ``[0, 100]``.
  - ``-10``\ :sup:```4```\ ``<= Node.val <= 10``\ :sup:```4```

  .. |image1| image:: https://assets.leetcode.com/uploads/2020/12/20/ex1.jpg
  .. |image2| image:: https://assets.leetcode.com/uploads/2020/12/20/ex2.jpg
  .. |image3| image:: https://assets.leetcode.com/uploads/2020/12/20/ex3.jpg
solutions:
- name: Recursive
  explanation: |
    Two tree are equal if and only if their roots are equal and their left and
    right subtrees are equal. To check if the left and right subtrees are equal, we
    can use recursion. If both roots are ``None``, then they are equal. If one is
    ``None`` and the other is not, then they are not equal.
  complexity: |
    :math:`n` is the number of nodes in tree 1

    .. list-table::
       :header-rows: 1
       :widths: auto

       * - Measure
         - Complexity
         - Notes
       * - Time
         - :math:`O(n)`
         - visit each node once
       * - Auxiliary Space
         - :math:`O(1)`
         -
