slug: reverse-string
patterns:
- Two Pointers
- String
description_rst: |
  Write a function that reverses a string. The input string is given as an
  array of characters ``s``.

  You must do this by modifying the input array
  `in-place <https://en.wikipedia.org/wiki/In-place_algorithm>`__ with
  ``O(1)`` extra memory.

   

  **Example 1:**

  ::

     Input: s = ["h","e","l","l","o"]
     Output: ["o","l","l","e","h"]

  **Example 2:**

  ::

     Input: s = ["H","a","n","n","a","h"]
     Output: ["h","a","n","n","a","H"]

   

  **Constraints:**

  - ``1 <= s.length <= 10``\ :sup:```5```
  - ``s[i]`` is a `printable ascii
    character <https://en.wikipedia.org/wiki/ASCII#Printable_characters>`__.
explanation: |
  Let :math:`n` be the length of the input list ``s``. Let ``end = n - 1``. We
  can reverse the list by swapping the outermost elements, moving inwards. ::

      s[i], s[end - i] = s[end - i], s[i]
complexity: |
  | :math:`n` is the length of the input string
  | Time: :math:`O(n)` — swap half the elements
  | Space: :math:`O(1)`
