slug: reorder-list
patterns:
- Linked List
- Two Pointers
- Stack
- Recursion
description_rst: "You are given the head of a singly linked-list. The list can be\nrepresented as:\n\n::\n\n\n   L0 → L1 → … → Ln - 1 → Ln\n\n*Reorder the list to be on the following form:*\n\n::\n\n\n   L0 → Ln → L1 → Ln - 1 → L2 → Ln - 2 → …\n\nYou may not modify the values in the list's nodes. Only nodes themselves\nmay be changed.\n\n \n\n**Example 1:**\n\n|image1|\n\n::\n\n\n   Input: head = [1,2,3,4]\n   Output: [1,4,2,3]\n\n**Example 2:**\n\n|image2|\n\n::\n\n\n   Input: head = [1,2,3,4,5]\n   Output: [1,5,2,4,3]\n\n \n\n**Constraints:**\n\n- The number of nodes in the list is in the range\n  ``[1, 5 * 10``\\ :sup:```4```\\ ``]``.\n- ``1 <= Node.val <= 1000``\n\n.. |image1| image:: https://assets.leetcode.com/uploads/2021/03/04/reorder1linked-list.jpg\n.. |image2| image:: https://assets.leetcode.com/uploads/2021/03/09/reorder2-linked-list.jpg\n"
solutions:
- name: Split And Merge
  explanation: ''
  complexity: ''
