slug: longest-common-prefix
patterns:
- Array
- String
- Trie
description_rst: |
  Write a function to find the longest common prefix string amongst an
  array of strings.

  If there is no common prefix, return an empty string ``""``.

   

  **Example 1:**

  ::


     Input: strs = ["flower","flow","flight"]
     Output: "fl"

  **Example 2:**

  ::


     Input: strs = ["dog","racecar","car"]
     Output: ""
     Explanation: There is no common prefix among the input strings.

   

  **Constraints:**

  - ``1 <= strs.length <= 200``
  - ``0 <= strs[i].length <= 200``
  - ``strs[i]`` consists of only lowercase English letters if it is
    non-empty.
solutions:
- name: Approach 1
  explanation: |
    Iterate through each character in the shortest string and check if it is in all
    other strings in ``strs``.
  complexity: |
    | :math:`n` is the number of strings in the input list and :math:`m` is the length of the shortest string
    | Time: :math:`O(n m)` — :math:`n` strings, :math:`m` prefix length
    | Auxiliary Space: :math:`O(1)`
