slug: valid-palindrome
patterns:
- Two Pointers
- String
description_rst: |
  A phrase is a **palindrome** if, after converting all uppercase letters
  into lowercase letters and removing all non-alphanumeric characters, it
  reads the same forward and backward. Alphanumeric characters include
  letters and numbers.

  Given a string ``s``, return ``true`` *if it is a* **palindrome**\ *,
  or* ``false`` *otherwise*.



  **Example 1:**

  ::


     Input: s = "A man, a plan, a canal: Panama"
     Output: true
     Explanation: "amanaplanacanalpanama" is a palindrome.

  **Example 2:**

  ::


     Input: s = "race a car"
     Output: false
     Explanation: "raceacar" is not a palindrome.

  **Example 3:**

  ::


     Input: s = " "
     Output: true
     Explanation: s is an empty string "" after removing non-alphanumeric characters.
     Since an empty string reads the same forward and backward, it is a palindrome.



  **Constraints:**

  - ``1 <= s.length <= 2 * 10``\ :sup:```5```
  - ``s`` consists only of printable ASCII characters.
solutions:
- name: Two Pointers
  explanation: |
    First, we convert ``s`` to all lowercase. Rather than remove all
    non-alphanumeric characters, we can ignore them when checking if ``s`` is a
    palindrome. We do this by using two pointers ``i`` and ``j`` at the beginning
    of ``s`` and at the end of ``s``. When both pointers are on non-alphanumeric
    characters, move them inwards.
  complexity: |
    :math:`n` is the length of ``s``.

    .. list-table::
       :header-rows: 1
       :widths: auto

       * - Measure
         - Complexity
         - Notes
       * - Time
         - :math:`O(n)`
         - single pass through ``s``.
       * - Auxiliary Space
         - :math:`O(n)`
         - lowercase copy
