slug: bitwise-and-of-numbers-range
patterns:
- Bit Manipulation
description_rst: |
  Given two integers ``left`` and ``right`` that represent the range
  ``[left, right]``, return *the bitwise AND of all numbers in this range,
  inclusive*.

   

  **Example 1:**

  ::


     Input: left = 5, right = 7
     Output: 4

  **Example 2:**

  ::


     Input: left = 0, right = 0
     Output: 0

  **Example 3:**

  ::


     Input: left = 1, right = 2147483647
     Output: 0

   

  **Constraints:**

  - ``0 <= left <= right <= 2``\ :sup:```31```\ ``- 1``
solutions:
- name: Common Prefix
  explanation: |
    Consider 2 binary numbers :math:`left < right`. Observe that :math:`left` and
    :math:`left + 1` differ only in the 1's bit. Then :math:`left \land (left + 1)`
    is :math:`left` with the last bit set to 0. Similarly, :math:`left + 1` differ
    in the 2's bit, so :math:`left \land (left + 1) \land (left + 2)` is
    :math:`left` with the last 2 bits set to 0. The bitwise :math:`\land` of all
    binary numbers in :math:`[left, right]` is the common prefix of :math:`left`
    and :math:`right` with all other bits set to 0, as the subsequent bits will
    vary in :math:`[left, right]`.
  complexity: |
    | Time: :math:`O(1)` — at most 32 bit comparisons
    | Auxiliary Space: :math:`O(1)`
